language: node_js
node_js:
  - '6'
script:
  - node build.js
branches:
  only:
    - master
env:
  global:
    secure: "I/yieU6Gc1gogf3lCIG6maqEq3Ru/yCGcWTPWF099HPsnNFkxDz/IMbdFWh7lYypJQ33iDoLEfmv4gxoxxz+B5bJXW9UHzAGrGV7wQbtD1v0hHAwsArmnDNsVYkSENh0fa0xDEuqGLljgrkJBDeEGKnCX2zRIuA9u/3f4znsL6k"
