language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
branches:
  only:
  - master
env:
  global:
    secure: HugJ1uFWMLRnYrJ3HKd7v8QiouUh2YaGwJhGiyFBLbUPUyO55jkL9xzW2HHxSFyqudNsUmDEkzhSjJ02Tw+oD0MGUCRRYcUfMwNfWn18eMcDLEWxnLA/DOZ4fNTxMMwPP6L3mfAxlPvzjo6W27DO2BId7aVF+9pfGfiulGUuo5E=
